baseurl = "https://stepzep.com"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 7
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Stephanie Zepeda"
    subtitle = "Robotics Enthusiast"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "My blog"
      logoHomeLink = "/"

    [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "About me"
      name = "About me"
      url = "/about/about"
    [[languages.en.menu.main]]
      identifier = "Project"
      name = "Projects"
      url = "/projects"
    [[languages.en.menu.main]]
      identifier = "Articles"
      name = "Articles"
      url = "/articles"
      [[languages.en.menu.main]]
        identifier = "R2D2"
        name = "R2D2"
        url = "/R2D2"
